site_name: arXiv CE

docs_dir: docs

# Forces links in the format /help/index.html instead of mkdocs default of /help
# This allows us serve as totally static with no support from a web server
use_directory_urls: false

plugins:
  - search
theme:
  name: material
  logo: arxiv-logomark-small.svg
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
#  custom_dir: overrides
# extra_css:
#   - stylesheets/extra.css

repo_name: GitHub
repo_url: https://github.com/arXiv/discussion/docs
edit_uri: blob/master/mkdocs/docs